name: Jikka
version: 5.4.0.0
github: "kmyk/Jikka"
license: Apache
author: "Kimiyuki Onaka"
maintainer: "kimiyuk95@gmail.com"
copyright: "2021 Kimiyuki Onaka"

extra-source-files:
  - README.md
  - CHANGELOG.md

data-files:
  - runtime/include/jikka/*.hpp

# Metadata used when publishing your package
synopsis: A transpiler from Python to C++ for competitive programming
category: "Compilers/Interpreters"

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kmyk/Jikka>

dependencies:
  - ansi-terminal    >= 0.11 && < 0.12
  - array            >= 0.5.3 && < 0.6
  - base             >= 4.12 && < 5
  - containers       >= 0.6.0 && < 0.7
  - deepseq          >= 1.4.4 && < 1.5
  - directory        >= 1.3.3 && < 1.4
  - mtl              >= 2.2.2 && < 2.3
  - template-haskell >= 2.15.0 && < 2.17
  - text             >= 1.2.3 && < 1.3
  - transformers     >= 0.5.6 && < 0.6
  - vector           >= 0.12.3 && < 0.13

flags:
  embed-runtime:
    description: Embed files under runtime/include/ to the compiled binary.
    default: False
    manual: True
# `if flag(..)` confuses ahc-cabal of the current Asterius (2021-08-31).
#  compile-web-assembly:
#    description: Use Asterius and compile Jikka to WebAssembly.
#    default: False
#    manual: True

library:
  source-dirs: src

  build-tools:
    - alex
    - happy

  ghc-options:
    - -W
    - -optP-Wno-nonportable-include-path

  when:
    - condition: flag(embed-runtime)
      cpp-options: -DJIKKA_EMBED_RUNTIME

executables:
  jikka:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -W
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optP-Wno-nonportable-include-path
    dependencies:
      - Jikka

# `import Asterius.Types` in asterius.hs breaks normal builds.
#ASTERIUS  jikka-asterius:
#ASTERIUS    main: asterius.hs
#ASTERIUS    source-dirs: app
#ASTERIUS    ghc-options:
#ASTERIUS      - -W
#ASTERIUS      - -threaded
#ASTERIUS      - -rtsopts
#ASTERIUS      - -with-rtsopts=-N
#ASTERIUS      - -optP-Wno-nonportable-include-path
#ASTERIUS      - -optl--export-function=convert
#ASTERIUS    dependencies:
#ASTERIUS      - Jikka

tests:
  jikka-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -W
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optP-Wno-nonportable-include-path
    dependencies:
      - Jikka
      - ormolu
      - hlint
      - hspec
    build-tools:
      - hspec-discover

  jikka-doctest:
    main: doctests.hs
    source-dirs: app
    ghc-options:
      - -W
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optP-Wno-nonportable-include-path
    dependencies:
      - Jikka
      - doctest
