#!/usr/bin/env python3
# https://atcoder.jp/contests/abc200/submissions/22401491


def solve(n: int, k: int) -> int:
    for _ in range(k):
        if n % 200 == 0:
            n //= 200
        else:
            n = n * 1000 + 200
    return n


# generated by oj-template v4.7.2 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    a = solve(N, K)
    print(a)


if __name__ == '__main__':
    main()
