#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.0 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10**5)
    K = random.randint(1, 20)
    print(N, K)


if __name__ == "__main__":
    main()
