#include <cstdint>
#include <iostream>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int64_t N, int64_t K) {
  uint64_t ans = 0;
  for (int i = 1; i <= N; ++i) {
    for (int j = 1; j <= K; ++j) {
      ans += 100 * i + j;
    }
  }
  return ans;
}

// generated by oj-template v4.8.1
// (https://github.com/online-judge-tools/template-generator)
int main() {
  std::ios::sync_with_stdio(false);
  std::cin.tie(nullptr);
  int64_t N, K;
  std::cin >> N >> K;
  auto ans = solve(N, K);
  std::cout << ans << '\n';
  return 0;
}
