#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = random.randint(1, 10**5)
    B = random.randint(1, 10**5)
    C = random.randint(1, 10**5)
    D = random.randint(1, 10**5)
    print(A, B, C, D)


if __name__ == "__main__":
    main()
