import Test.DocTest

-- | The modules generated by alex and happy confuse doctest, so we need to avoid some modules which depend on them.
-- TODO: Resolve this issue.
--
-- >   main = doctest ["-isrc", "src/Jikka/Main.hs"]
main :: IO ()
main =
  doctest
    [ "src/Jikka/Common/",
      "src/Jikka/Python/Convert/",
      "src/Jikka/Python/Language/",
      "src/Jikka/RestrictedPython/Language/"
    ]
